---
title: "Simulation study"
author: "August Arnstad"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(formatR)
showsol <- FALSE
library(knitr)
library(devtools)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 68), 
                      tidy = TRUE, 
                      warning = FALSE, 
                      error = FALSE, 
                      message = FALSE, 
                      echo = TRUE, 
                      fig.width=7, 
                      fig.height=5, 
                      fig.align="center")

library(remotes)
library(devtools)
if(!require(devtools)) install.packages("devtools")
devtools::install_github("AugustArnstad/BayesianVariableImportance")
library(BayesianVariableImportance)
library(INLA)
library(MASS)
library(dplyr)
```


```{r}

simulate_data <- function(n = 10000, n_groups = 100, covariance_level=0) {
  # Simulate fixed effects
  
  sigma <- matrix(c(1, covariance_level, covariance_level, 
                    covariance_level, 1, covariance_level, 
                    covariance_level, covariance_level, 1), 3, 3)
  
  X <- MASS::mvrnorm(n = n, mu = c(0, 0, 0), Sigma = sigma)
  X1 <- X[, 1]
  X2 <- X[, 2]
  X3 <- X[, 3]

  # Simulate random effects groups
  Z1 <- sample(1:n_groups, n, replace = TRUE)
  random_effect_contributions_z1 <- rnorm(n_groups, mean = 0, sd = 1)[Z1]

  # Coefficients for fixed effects
  beta1 <- 1
  beta2 <- sqrt(2)
  beta3 <- sqrt(3)

  # Linear predictor
  eta <- beta1*X1 + beta2*X2 + beta3*X3 + random_effect_contributions_z1

  # Binomial with logit link
  p_logit <- exp(eta) / (1 + exp(eta))
  y_logit_bin <- rbinom(n, size = 1, prob = p_logit)
  data_logit <- data.frame(y_logit_bin, X1, X2, X3, Z1)

  # Binomial with probit link
  p_probit <- pnorm(eta)
  y_probit_bin <- rbinom(n, size = 1, prob = p_probit)
  data_probit <- data.frame(y_probit_bin, X1, X2, X3, Z1)

  # Poisson with log link
  lambda <- exp(eta)
  y_pois <- rpois(n, lambda = lambda)
  data_poisson <- data.frame(y_pois, X1, X2, X3, Z1)
  
  epsilon = rnorm(n, mean=0, sd=sqrt(1))
  y_normal <-  beta1*X[, 1] + beta2*X[, 2] + beta3*X[, 3] + random_effect_contributions_z1 + epsilon 
  data_normal <- data.frame(y_normal, X1, X2, X3, Z1)
  
  
  list(binomial_logit = data_logit, 
       binomial_probit = data_probit, 
       poisson = data_poisson, 
       normal = data_normal)
}

```



```{r}
extract_importance <- function(model, data, dist_factor) {
  # Decompose fixed effects matrix using SVD
  SVD <- BayesianVariableImportance::SVD_decomp(data[, c("X1", "X2", "X3")])
  
  # Sample from the posterior distribution
  sample_post <- inla.posterior.sample(model, n = 1)
  
  # Extract latent effects names
  latent_names <- rownames(sample_post[[1]]$latent)
  
  # Identify random effects using the pattern
  pattern_random <- paste0("^", "Z1", ":")
  random_indices <- grep(pattern_random, latent_names, value = TRUE)
  random_samples <- sample_post[[1]]$latent[random_indices, , drop = FALSE]
  
  # Variance of random effects
  var_random <- var(random_samples)
  
  # Process fixed effects
  fixed_effects <- numeric(3)
  fixed_imp <- numeric(3)
  for (i in 1:3) {
    fixed_indices <- grep(paste0("^", "X", i, ":"), latent_names, value = TRUE)
    fixed_samples <- sample_post[[1]]$latent[fixed_indices, , drop = FALSE]

    fixed_effects[i] <- fixed_samples
  }

  
  fixed_imp <- (SVD$lambda^2 %*% (fixed_effects^2))

  
  # Calculate overall importances
  total_var = as.double(dist_factor + var_random + sum(fixed_imp))
  
  imp_random <- var_random / total_var
  imp_fixed <- fixed_imp / total_var
  
  r2m <- sum(fixed_imp) / total_var
  r2c <- (sum(fixed_imp) + var_random) / total_var
  
  # Returning as a list
  list(
    random_importance = imp_random,
    fixed_importance = imp_fixed,
    r2m = r2m,
    r2c = r2c,
    expected_importance = (1) / (dist_factor + 1 + 2 + 3 + 1),
    expected_r2m = (1 + 2 + 3) / (dist_factor + 1 + 2 + 3 + 1),
    expected_r2c = (1 + 2 + 3 + 1) / (dist_factor + 1 + 2 + 3 + 1)
  )
}


# Example of how you might integrate this into your simulation function
run_simulation <- function(n_sim = 5, covariance_level = 0, include_probit = FALSE) {
  importances <- vector("list", n_sim)
  failed_simulations <- list()
  
  pb <- txtProgressBar(min = 0, max = n_sim, initial = 0, style = 3)
  
  for (i in 1:n_sim) {
    
    tryCatch({
    datasets <- simulate_data(covariance_level = covariance_level)

    
    glmm_logit <- y_logit_bin ~ X1 + X2 + X3 + f(Z1, model="iid", hyper=list(prec = list(
        prior = "pc.prec",
        param = c(1, 0.01),
        initial = log(1)
      )))
    glmm_pois <- y_pois ~ X1 + X2 + X3 + f(Z1, model="iid", hyper=list(prec = list(
        prior = "pc.prec",
        param = c(1, 0.01),
        initial = log(1)
      )))
    
    model_logit <- BayesianVariableImportance::perform_inla_analysis(datasets$binomial_logit, glmm_logit, family = "binomial", link_func = "logit")
    model_pois <- BayesianVariableImportance::perform_inla_analysis(datasets$poisson, glmm_pois, family = "poisson", link_func = "log")
    
    importances[[i]] <- list(
      logit = extract_importance(model_logit, datasets$binomial_logit, pi^2 / 3),
      poisson = extract_importance(model_pois, datasets$poisson, log(1 + 1/exp(summary(model_pois)$fixed[1] + 0.5)))
    )
    
    if (include_probit) {
      glmm_probit <- y_probit_bin ~ X1 + X2 + X3 + f(Z1, model="iid", hyper=list(prec = list(
        prior = "pc.prec",
        param = c(1, 0.01),
        initial = log(1)
      )))
      model_probit <- BayesianVariableImportance::perform_inla_analysis(datasets$binomial_probit, glmm_probit, family = "binomial", link_func = "probit")
      importances[[i]]$probit = extract_importance(model_probit, datasets$binomial_probit, 1)
    }
    setTxtProgressBar(pb, i)
    }, error = function(e) {
      failed_simulations[[length(failed_simulations) + 1]] <- list(
        sim_number = i,
        error_message = conditionMessage(e),
        parameters = list(covariance_level = covariance_level)  # Add other relevant parameters here
        )
      cat("Error in simulation", i, ":", conditionMessage(e), "\n")
    # Optionally, retry or modify parameters slightly and retry
  })
    
  }
  close(pb)
  return(list(successes = importances, failures = failed_simulations))
}

```


```{r}

n_sims <- 500

sims_count <- c(0, 0, 0, 0, 0)

sim_no <- run_simulation(n_sim=n_sims, covariance_level=0, include_probit=FALSE)

sims_count <- c(1, 0, 0, 0, 0)

sim_low_pos <- run_simulation(n_sim=n_sims, covariance_level=0.1, include_probit=FALSE)

sims_count <- c(1, 1, 0, 0, 0)

sim_low_neg <- run_simulation(n_sim=n_sims, covariance_level=-0.1, include_probit=FALSE)

sims_count <- c(1, 1, 1, 0, 0)

sim_high_pos <- run_simulation(n_sim=n_sims, covariance_level=0.4, include_probit=FALSE)

sims_count <- c(1, 1, 1, 1, 0)

sim_high_neg <- run_simulation(n_sim=n_sims, covariance_level=-0.4, include_probit=FALSE)

sims_count <- c(1, 1, 1, 1, 1)

sims_count
```

```{r}
# Saving the entire loaded_sim_no$successes object as an RDS file
setwd("/Users/augustarnstad/Library/CloudStorage/OneDrive-NTNU/Semester_10/R kladd/Simulation study results")
saveRDS(sim_no, "simulation_no_corr_04.05.rds")
saveRDS(sim_low_pos, "simulation_low_pos_corr_04.05.rds")
saveRDS(sim_low_neg, "simulation_low_neg_corr_04.05.rds")
saveRDS(sim_high_pos, "simulation_high_pos_corr_04.05.rds")
saveRDS(sim_high_neg, "simulation_high_neg_corr_04.05.rds")
```

```{r}
# To load this file back into R:
setwd("/Users/augustarnstad/Library/CloudStorage/OneDrive-NTNU/Semester_10/R kladd/Simulation study results")
loaded_sim_no <- readRDS("simulation_no_corr_04.05.rds")
loaded_sim_low_pos <- readRDS("simulation_low_pos_corr_04.05.rds")
loaded_sim_low_neg <- readRDS("simulation_low_neg_corr_04.05.rds")
loaded_sim_high_pos <- readRDS("simulation_high_pos_corr_04.05.rds")
loaded_sim_high_neg <- readRDS("simulation_high_neg_corr_04.05.rds")

```



```{r}
#Kjør dette over natta! Ikke kjør det før møtet kanskje?
# rptR_probit <- rptBinary(y_probit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
#     c("Fixed", "Z1"), data = datasets$binomial_probit, nboot = 100, npermut = 0, link="probit", adjusted = FALSE)

datasets_no <- simulate_data()
datasets_low_pos <- simulate_data(covariance_level = 0.1)
datasets_low_neg <- simulate_data(covariance_level = -0.1)
datasets_high_pos <- simulate_data(covariance_level = 0.4)
datasets_high_neg <- simulate_data(covariance_level = -0.4)



library(rptR)
rptR_logit_no <- rptBinary(y_logit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_no$binomial_logit, nboot = 100, npermut = 0, link="logit", adjusted = FALSE)
rptR_pois_no <- rptPoisson(y_pois ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_no$poisson, link="log", nboot = 100, npermut = 0, adjusted=FALSE)



rptR_logit_low_pos <- rptBinary(y_logit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_low_pos$binomial_logit, nboot = 100, npermut = 0, link="logit", adjusted = FALSE)
rptR_pois_low_pos <- rptPoisson(y_pois ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_low_pos$poisson, link="log", nboot = 100, npermut = 0, adjusted=FALSE)




rptR_logit_low_neg <- rptBinary(y_logit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_low_neg$binomial_logit, nboot = 100, npermut = 0, link="logit", adjusted = FALSE)
rptR_pois_low_neg <- rptPoisson(y_pois ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_low_neg$poisson, link="log", nboot = 100, npermut = 0, adjusted=FALSE)



rptR_logit_high_pos <- rptBinary(y_logit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_high_pos$binomial_logit, nboot = 100, npermut = 0, link="logit", adjusted = FALSE)
rptR_pois_high_pos <- rptPoisson(y_pois ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_high_pos$poisson, link="log", nboot = 100, npermut = 0, adjusted=FALSE)



rptR_logit_high_neg <- rptBinary(y_logit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_high_neg$binomial_logit, nboot = 100, npermut = 0, link="logit", adjusted = FALSE)
rptR_pois_high_neg <- rptPoisson(y_pois ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets_high_neg$poisson, link="log", nboot = 100, npermut = 0, adjusted=FALSE)
```

```{r}
setwd("/Users/augustarnstad/Library/CloudStorage/OneDrive-NTNU/Semester_10/R kladd/Simulation study results")
saveRDS(rptR_logit_no, "stoffel_sim_logit_no_corr_05.05.rds")
saveRDS(rptR_pois_no, "stoffel_sim_pois_no_corr_05.05.rds")

saveRDS(rptR_logit_low_pos, "stoffel_sim_logit_low_pos_corr_05.05.rds")
saveRDS(rptR_pois_low_pos, "stoffel_sim_pois_low_pos_corr_05.05.rds")

saveRDS(rptR_logit_low_neg, "stoffel_sim_logit_low_neg_corr_05.05.rds")
saveRDS(rptR_pois_low_neg, "stoffel_sim_pois_low_neg_corr_05.05.rds")

saveRDS(rptR_logit_high_pos, "stoffel_sim_logit_high_pos_corr_05.05.rds")
saveRDS(rptR_pois_high_pos, "stoffel_sim_pois_high_pos_corr_05.05.rds")

saveRDS(rptR_logit_high_neg, "stoffel_sim_logit_high_neg_corr_05.05.rds")
saveRDS(rptR_pois_high_neg, "stoffel_sim_pois_high_neg_corr_05.05.rds")
```

```{r}
rptR_logit_no <- readRDS("stoffel_sim_logit_no_corr_05.05.rds")
rptR_pois_no <- readRDS("stoffel_sim_pois_no_corr_05.05.rds")

rptR_logit_low_pos <- readRDS("stoffel_sim_logit_low_pos_corr_05.05.rds")
rptR_pois_low_pos <- readRDS("stoffel_sim_pois_low_pos_corr_05.05.rds")

rptR_logit_low_neg <- readRDS("stoffel_sim_logit_low_neg_corr_05.05.rds")
rptR_pois_low_neg <- readRDS("stoffel_sim_pois_low_neg_corr_05.05.rds")

rptR_logit_high_pos <- readRDS("stoffel_sim_logit_high_pos_corr_05.05.rds")
rptR_pois_high_pos <- readRDS("stoffel_sim_pois_high_pos_corr_05.05.rds")

rptR_logit_high_neg <- readRDS("stoffel_sim_logit_high_neg_corr_05.05.rds")
rptR_pois_high_neg <- readRDS("stoffel_sim_pois_high_neg_corr_05.05.rds")
```


```{r}
Stoffel_logit_no <- rptR_logit_no$R$Z1[2]
Stoffel_pois_no <- rptR_pois_no$R$Z1[2]

Stoffel_logit_low_pos <- rptR_logit_low_pos$R$Z1[2]
Stoffel_pois_low_pos <- rptR_pois_low_pos$R$Z1[2]

Stoffel_logit_low_neg <- rptR_logit_low_neg$R$Z1[2]
Stoffel_pois_low_neg <- rptR_pois_low_neg$R$Z1[2]

Stoffel_logit_high_pos <- rptR_logit_high_pos$R$Z1[2]
Stoffel_pois_high_pos <- rptR_pois_high_pos$R$Z1[2]

Stoffel_logit_high_neg <- rptR_logit_high_neg$R$Z1[2]
Stoffel_pois_high_neg <- rptR_pois_high_neg$R$Z1[2]



Stoffel_logit_R2m_no <- rptR_logit_no$R$Fixed[2]
Stoffel_pois_R2m_no <- rptR_pois_no$R$Fixed[2]

Stoffel_logit_R2m_low_pos <- rptR_logit_low_pos$R$Fixed[2]
Stoffel_pois_R2m_low_pos <- rptR_pois_low_pos$R$Fixed[2]

Stoffel_logit_R2m_low_neg <- rptR_logit_low_neg$R$Fixed[2]
Stoffel_pois_R2m_low_neg <- rptR_pois_low_neg$R$Fixed[2]

Stoffel_logit_R2m_high_pos <- rptR_logit_high_pos$R$Fixed[2]
Stoffel_pois_R2m_high_pos <- rptR_pois_high_pos$R$Fixed[2]

Stoffel_logit_R2m_high_neg <- rptR_logit_high_neg$R$Fixed[2]
Stoffel_pois_R2m_high_neg <- rptR_pois_high_neg$R$Fixed[2]


Stoffel_logit_R2c_no <- rptR_logit_no$R$Fixed[2] + rptR_logit_no$R$Z1[2]
Stoffel_pois_R2c_no <- rptR_pois_no$R$Fixed[2] + rptR_pois_no$R$Z1[2]

Stoffel_logit_R2c_low_pos <- rptR_logit_low_pos$R$Fixed[2] + rptR_logit_low_pos$R$Z1[2]
Stoffel_pois_R2c_low_pos <- rptR_pois_low_pos$R$Fixed[2] + rptR_pois_low_pos$R$Z1[2]

Stoffel_logit_R2c_low_neg <- rptR_logit_low_neg$R$Fixed[2] + rptR_logit_low_neg$R$Z1[2]
Stoffel_pois_R2c_low_neg <- rptR_pois_low_neg$R$Fixed[2] + rptR_pois_low_neg$R$Z1[2]

Stoffel_logit_R2c_high_pos <- rptR_logit_high_pos$R$Fixed[2] + rptR_logit_high_pos$R$Z1[2]
Stoffel_pois_R2c_high_pos <- rptR_pois_high_pos$R$Fixed[2] + rptR_pois_high_pos$R$Z1[2]

Stoffel_logit_R2c_high_neg <- rptR_logit_high_neg$R$Fixed[2] + rptR_logit_high_neg$R$Z1[2]
Stoffel_pois_R2c_high_neg <- rptR_pois_high_neg$R$Fixed[2] + rptR_pois_high_neg$R$Z1[2]

```


```{r}
# Function to extract averages and 95% quantiles for a given model
extract_averages_and_quantiles <- function(sim_data, model) {
  # Collect all fixed effect importances
  fixed_importances_list <- lapply(sim_data, function(x) t(x[[model]]$fixed_importance))
  fixed_importances <- do.call(rbind, fixed_importances_list)
  
  # Calculate average and 95% quantile for fixed effects
  average_fixed_importance <- colMeans(fixed_importances)
  quantile_fixed_importance <- apply(fixed_importances, 2, quantile, probs = c(0.025, 0.975))

  # Collect random importance, R2m, R2c, and expected importance
  random_importances <- sapply(sim_data, function(x) x[[model]]$random_importance)
  r2m_values <- sapply(sim_data, function(x) x[[model]]$r2m)
  r2c_values <- sapply(sim_data, function(x) x[[model]]$r2c)
  expected_importances <- sapply(sim_data, function(x) x[[model]]$expected_importance)
  expected_r2m <- sapply(sim_data, function(x) x[[model]]$expected_r2m)
  expected_r2c <- sapply(sim_data, function(x) x[[model]]$expected_r2c)

  # Calculate mean and 95% quantile for each metric
  average_random_importance <- mean(random_importances)
  quantile_random_importance <- quantile(random_importances, probs = c(0.025, 0.975))

  average_r2m <- mean(r2m_values)
  quantile_r2m <- quantile(r2m_values, probs = c(0.025, 0.975))

  average_r2c <- mean(r2c_values)
  quantile_r2c <- quantile(r2c_values, probs = c(0.025, 0.975))

  average_expected_importance <- mean(expected_importances)
  quantile_expected_importance <- quantile(expected_importances, probs = c(0.025, 0.975))
  
  average_expected_r2m <- mean(expected_r2m)
  quantile_expected_r2m <- quantile(expected_r2m, probs = c(0.025, 0.975))
  
  average_expected_r2c <- mean(expected_r2c)
  quantile_expected_r2c <- quantile(expected_r2c, probs = c(0.025, 0.975))

  list(
    average_random_importance = average_random_importance,
    quantile_random_importance = quantile_random_importance,
    average_fixed_importance = average_fixed_importance,
    quantile_fixed_importance = quantile_fixed_importance,
    average_r2m = average_r2m,
    quantile_r2m = quantile_r2m,
    average_r2c = average_r2c,
    quantile_r2c = quantile_r2c,
    average_expected_importance = average_expected_importance,
    quantile_expected_importance = quantile_expected_importance,
    average_expected_r2m = average_expected_r2m,
    quantile_expected_r2m = quantile_expected_r2m,
    average_expected_r2c = average_expected_r2c,
    quantile_expected_r2c = quantile_expected_r2c
  )
}



filter_successes <- function(sim_data, model) {
  Filter(function(x) !is.null(x[[model]]$fixed_importance), sim_data)
}


success_no_bin <- filter_successes(loaded_sim_no$successes, "logit")
success_low_pos_bin <- filter_successes(loaded_sim_low_pos$successes, "logit")
success_low_neg_bin <- filter_successes(loaded_sim_low_neg$successes, "logit")
success_high_pos_bin <- filter_successes(loaded_sim_high_pos$successes, "logit")
success_high_neg_bin <- filter_successes(loaded_sim_high_neg$successes, "logit")



averages_logit_no <- extract_averages_and_quantiles(success_no_bin, "logit")
averages_logit_low_pos <- extract_averages_and_quantiles(success_low_pos_bin, "logit")
averages_logit_low_neg <- extract_averages_and_quantiles(success_low_neg_bin, "logit")
averages_logit_high_pos <- extract_averages_and_quantiles(success_high_pos_bin, "logit")
averages_logit_high_neg <- extract_averages_and_quantiles(success_high_neg_bin, "logit")


print("Logit Model - Averages and Quantiles:")
print(averages_logit_no)
print(averages_logit_low_pos)
print(averages_logit_low_neg)
print(averages_logit_high_pos)
print(averages_logit_high_neg)



count_failures <- function(sim_data, model) {
  sum(sapply(sim_data, function(x) is.null(x[[model]]$fixed_importance)))
}


num_failures_logit_no <- count_failures(loaded_sim_no$successes, "logit")
print(paste("Number of failed logit simulations:", num_failures_logit_no))
num_failures_logit_low_pos <- count_failures(loaded_sim_low_pos$successes, "logit")
print(paste("Number of failed logit simulations:", num_failures_logit_low_pos))
num_failures_logit_low_neg <- count_failures(loaded_sim_low_neg$successes, "logit")
print(paste("Number of failed logit simulations:", num_failures_logit_low_neg))
num_failures_logit_high_pos <- count_failures(loaded_sim_high_pos$successes, "logit")
print(paste("Number of failed logit simulations:", num_failures_logit_high_pos))
num_failures_logit_high_neg <- count_failures(loaded_sim_high_neg$successes, "logit")
print(paste("Number of failed logit simulations:", num_failures_logit_high_neg))



success_no_pois <- filter_successes(loaded_sim_no$successes, "poisson")
success_low_pos_pois <- filter_successes(loaded_sim_low_pos$successes, "poisson")
success_low_neg_pois <- filter_successes(loaded_sim_low_neg$successes, "poisson")
success_high_pos_pois <- filter_successes(loaded_sim_high_pos$successes, "poisson")
success_high_neg_pois <- filter_successes(loaded_sim_high_neg$successes, "poisson")

averages_poisson_no <- extract_averages_and_quantiles(success_no_pois, "poisson")
averages_poisson_low_pos <- extract_averages_and_quantiles(success_low_pos_pois, "poisson")
averages_poisson_low_neg <- extract_averages_and_quantiles(success_low_neg_pois, "poisson")
averages_poisson_high_pos <- extract_averages_and_quantiles(success_high_pos_pois, "poisson")
averages_poisson_high_neg <- extract_averages_and_quantiles(success_high_neg_pois, "poisson")

print("Poisson Model - Averages and Quantiles:")
print(averages_poisson_no)
print(averages_poisson_low_pos)
print(averages_poisson_low_neg)
print(averages_poisson_high_pos)
print(averages_poisson_high_neg)

num_failures_pois_no <- count_failures(loaded_sim_no$successes, "poisson")
print(paste("Number of failed logit simulations:", num_failures_pois_no))
num_failures_pois_low_pos <- count_failures(loaded_sim_low_pos$successes, "poisson")
print(paste("Number of failed logit simulations:", num_failures_pois_low_pos))
num_failures_pois_low_neg <- count_failures(loaded_sim_low_neg$successes, "poisson")
print(paste("Number of failed logit simulations:", num_failures_pois_low_neg))
num_failures_pois_high_pos <- count_failures(loaded_sim_high_pos$successes, "poisson")
print(paste("Number of failed logit simulations:", num_failures_pois_high_pos))
num_failures_pois_high_neg <- count_failures(loaded_sim_high_neg$successes, "poisson")
print(paste("Number of failed logit simulations:", num_failures_pois_high_neg))


for (i in 1:416){
  if (success_high_pos_pois[[i]]$poisson$fixed_importance[1] <= 0.05){
    print(success_high_pos_pois[[i]]$poisson$fixed_importance[1])
  }
}


for (i in 1:416){
  if (success_high_pos_pois[[i]]$poisson$fixed_importance[2] <= 0.05){
    print(success_high_pos_pois[[i]]$poisson$fixed_importance[2])
  }
}

for (i in 1:416){
  if (success_high_pos_pois[[i]]$poisson$fixed_importance[3] <= 0.05){
    print(success_high_pos_pois[[i]]$poisson$fixed_importance[3])
  }
}

for (i in 1:416){
  if (success_high_pos_pois[[i]]$poisson$random_importance >= 0.4){
    print(success_high_pos_pois[[i]]$poisson$random_importance)
  }
}

```


```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)
library(latex2exp)
library(scales)
library(pacman)
pacman::p_load(devtools)
pacman::p_load(ggplot2)
pacman::p_load(latex2exp)


random_importances_logit <- bind_rows(
  data.frame(Model = "Logit", Correlation = "0", RandomImportance = sapply(success_no_bin, function(x) x$logit$random_importance), Stoffel = Stoffel_logit_no),
  data.frame(Model = "Logit", Correlation = "0.1", RandomImportance = sapply(success_low_pos_bin, function(x) x$logit$random_importance), Stoffel = Stoffel_logit_low_pos),
  data.frame(Model = "Logit", Correlation = "-0.1", RandomImportance = sapply(success_low_neg_bin, function(x) x$logit$random_importance), Stoffel = Stoffel_logit_low_neg),
  data.frame(Model = "Logit", Correlation = "0.4", RandomImportance = sapply(success_high_pos_bin, function(x) x$logit$random_importance), Stoffel = Stoffel_logit_high_pos),
  data.frame(Model = "Logit", Correlation = "-0.4", RandomImportance = sapply(success_high_neg_bin, function(x) x$logit$random_importance), Stoffel = Stoffel_logit_high_neg)
)


expected_importance <- loaded_sim_no$successes[[1]]$logit$expected_importance
random_importances_logit$ExpectedImportance <- expected_importance
random_importances_logit$ConditionalExpected <- ifelse(random_importances_logit$Correlation == "0",
                                                      random_importances_logit$ExpectedImportance, 
                                                      NA)

random_importances_logit$Correlation <- factor(random_importances_logit$Correlation,
                                             #levels = c("rho=-0.4", "rho=-0.1", "rho=0", "rho=0.1", "rho=0.4"),
                                             levels = c("-0.4", "-0.1", "0", "0.1", "0.4"),
                                             labels = c("-0.4", "-0.1", "0", "0.1", "0.4"))

appender <- function(string){ 
    TeX(paste("$\\rho = $", string))
}

means <- random_importances_logit %>%
  group_by(Correlation) %>%
  summarise(Mean = mean(RandomImportance))

# Plotting faceted histograms with conditional expected importance line
random_logit_plot <- ggplot(random_importances_logit, aes(x = RandomImportance, fill = Correlation)) +
  geom_histogram(bins = 30, alpha = 0.7) +
  facet_wrap(~ Correlation, scales = "free", nrow = 1, ncol = 5, labeller = as_labeller(appender, default = label_parsed)) +
  geom_vline(data = random_importances_logit, aes(xintercept = ConditionalExpected), color = "green", linetype = "dashed", linewidth = 1) +
  geom_point(data = means, aes(x = Mean, y = 0, fill = Correlation), shape = 21, size = 3, color = "black") +
  geom_point(data = random_importances_logit, aes(x = Stoffel, y = 0, fill = Correlation), size = 3, color = "orange") +
  labs(#title = "Random Importances Across Correlation Levels for Logit Model",
       x = "Random Importance", y = "Frequency") +
  scale_fill_manual(values = c("-0.4" = "#E6C6DF",
                               "-0.1" = "#D6C6E7",
                               "0" = "#C6CDF7",
                               "0.1" = "#B6D7F7",
                               "0.4" = "#C6F7CD"
                               )) +
  theme_minimal() +
  theme(legend.position = "none",
    strip.text.x = element_text(size = 18),
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12)
    ) +
  scale_x_continuous(breaks = function(x) pretty(x, n = 3), labels = label_number(accuracy = 0.01))


random_logit_plot


mean(random_importances_logit$RandomImportance[which(random_importances_logit$Correlation == "-0.4")]) - Stoffel_logit_high_neg

mean(random_importances_logit$RandomImportance[which(random_importances_logit$Correlation == "-0.1")]) - Stoffel_logit_low_neg

mean(random_importances_logit$RandomImportance[which(random_importances_logit$Correlation == "0")]) - Stoffel_logit_no

mean(random_importances_logit$RandomImportance[which(random_importances_logit$Correlation == "0.1")]) - Stoffel_logit_low_pos

mean(random_importances_logit$RandomImportance[which(random_importances_logit$Correlation == "0.4")]) - Stoffel_logit_high_pos


```


```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)
library(latex2exp)
library(scales)
library(pacman)
pacman::p_load(devtools)
pacman::p_load(ggplot2)
pacman::p_load(latex2exp)



random_importances_poisson <- bind_rows(
  data.frame(Model = "Poisson", Correlation = "0", RandomImportance = sapply(success_no_pois, function(x) x$poisson$random_importance), Stoffel = Stoffel_pois_no),
  data.frame(Model = "Poisson", Correlation = "0.1", RandomImportance = sapply(success_low_pos_pois, function(x) x$poisson$random_importance), Stoffel = Stoffel_pois_low_pos),
  data.frame(Model = "Poisson", Correlation = "-0.1", RandomImportance = sapply(success_low_neg_pois, function(x) x$poisson$random_importance), Stoffel = Stoffel_pois_low_neg),
  data.frame(Model = "Poisson", Correlation = "0.4", RandomImportance = sapply(success_high_pos_pois, function(x) x$poisson$random_importance), Stoffel = Stoffel_pois_high_pos),
  data.frame(Model = "Poisson", Correlation = "-0.4", RandomImportance = sapply(success_high_neg_pois, function(x) x$poisson$random_importance), Stoffel = Stoffel_pois_high_neg)
)


expected_importance <- loaded_sim_no$successes[[1]]$poisson$expected_importance
random_importances_poisson$ExpectedImportance <- expected_importance
random_importances_poisson$ConditionalExpected <- ifelse(random_importances_poisson$Correlation == "0",
                                                      random_importances_poisson$ExpectedImportance, 
                                                      NA)

random_importances_poisson$Correlation <- factor(random_importances_poisson$Correlation,
                                             #levels = c("rho=-0.4", "rho=-0.1", "rho=0", "rho=0.1", "rho=0.4"),
                                             levels = c("-0.4", "-0.1", "0", "0.1", "0.4"),
                                             labels = c("-0.4", "-0.1", "0", "0.1", "0.4"))

appender <- function(string){ 
    TeX(paste("$\\rho = $", string))
}

means <- random_importances_poisson %>%
  group_by(Correlation) %>%
  summarise(Mean = mean(RandomImportance))


random_poisson_plot <- ggplot(random_importances_poisson, aes(x = RandomImportance, fill = Correlation)) +
  geom_histogram(bins = 30, alpha = 0.7) +
  facet_wrap(~ Correlation, scales = "free", nrow = 1, ncol = 5, labeller = as_labeller(appender, default = label_parsed)) +
  geom_vline(data = random_importances_poisson, aes(xintercept = ConditionalExpected), color = "green", linetype = "dashed", linewidth = 1) +
  geom_point(data = means, aes(x = Mean, y = 0, fill = Correlation), shape = 21, size = 3, color = "black") +
  geom_point(data = random_importances_poisson, aes(x = Stoffel, y = 0, fill = Correlation), size = 3, color = "orange") +
  labs(#title = "Random Importances Across Correlation Levels for Logit Model",
       x = "Random Importance", y = "Frequency") +
  scale_fill_manual(values = c("-0.4" = "#E6C6DF",
                               "-0.1" = "#D6C6E7",
                               "0" = "#C6CDF7",
                               "0.1" = "#B6D7F7",
                               "0.4" = "#C6F7CD"
                               )) +
  theme_minimal() +
  theme(legend.position = "none",
    strip.text.x = element_text(size = 18),
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12)
    ) +
  scale_x_continuous(breaks = function(x) pretty(x, n = 3), labels = label_number(accuracy = 0.01))


random_poisson_plot

str(random_importances_poisson)

mean(random_importances_poisson[random_importances_poisson$Correlation == "-0.4", "RandomImportance"]) - Stoffel_pois_high_neg
mean(random_importances_poisson[random_importances_poisson$Correlation == "-0.1", "RandomImportance"]) - Stoffel_pois_low_neg
mean(random_importances_poisson[random_importances_poisson$Correlation == "0", "RandomImportance"]) - Stoffel_pois_no
mean(random_importances_poisson[random_importances_poisson$Correlation == "0.1", "RandomImportance"]) - Stoffel_pois_low_pos
mean(random_importances_poisson[random_importances_poisson$Correlation == "0.4", "RandomImportance"]) - Stoffel_pois_high_pos


```


```{r}
library(ggplot2)
library(dplyr)
library(patchwork)


plot_fixed_importances <- function(data, model_name, cov_level=0) {

  fixed_effects_data <- list()

  
  for (i in 1:3) {
    fixed_importances <- data.frame(
      Simulation = rep(1:length(data), each = 1),
      FixedEffect = paste0("X", i),
      Importance = sapply(data, function(x) x[[model_name]]$fixed_importance[i]),
      ExpectedImportance = (i * data[[1]][[model_name]]$expected_importance),
      Correlation = as.character(cov_level)
    ) 
    fixed_effects_data[[i]] <- fixed_importances
  }
  
  all_fixed_importances <- do.call(rbind, fixed_effects_data)
  all_fixed_importances$Importance <- round(all_fixed_importances$Importance, 4)
  

  expected <- 0
  if (model_name == "poisson") {
    expected <- 0.115624
  } else if (model_name == "logit") {
    expected <- 0.09718298
  }
  
  fill_color <- if (cov_level == -0.4) {
    "#E6C6DF"
  } else if (cov_level == -0.1) {
    "#D6C6E7"
  } else if (cov_level == 0) {
    "#C6CDF7"
  } else if (cov_level == 0.1) {
    "#B6D7F7"
  } else if (cov_level == 0.4) {
    "#C6F7CD"
  } else {
    "#FFFFFF"  # Default color (white) if no match found
  }

  means <- all_fixed_importances %>%
  group_by(FixedEffect) %>%
  summarise(Mean = mean(Importance))
  
  if (cov_level == 0) {
    ggplot(all_fixed_importances, aes(x = Importance)) +
    geom_histogram(bins = 75, fill = fill_color, alpha = 0.7) +
    #facet_wrap(~ FixedEffect, scales = "free") +
    facet_wrap(~ Correlation, scales = "free", labeller =as_labeller(appender, default = label_parsed)) +
    geom_vline(aes(xintercept = ExpectedImportance), color = "green", linetype = "solid", linewidth = 1) +
    geom_point(data = means, aes(x = Mean, y = 0, fill = FixedEffect), shape = 21, size = 3, color = "black", show.legend = F) +
    labs(#title = paste(title_prefix, "Fixed Effect Importances with Expected Importances"),
         x = "Fixed Effect Importance", y = "Frequency") +
    scale_fill_manual(values = c("X1" = fill_color,
                           "X2" = fill_color,
                           "X3" = fill_color
                           )) +
    theme_minimal() +
    theme(legend.position = "none",
    strip.text.x = element_text(size = 18),
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12)
    ) 
  } else {
    ggplot(all_fixed_importances, aes(x = Importance)) +
    geom_histogram(bins = 75, fill = fill_color, alpha = 0.7) +
    #facet_wrap(~ FixedEffect, scales = "free") +
    facet_wrap(~ Correlation, scales = "free", labeller = as_labeller(appender, default = label_parsed)) +
    geom_point(data = means, aes(x = Mean, y = 0, fill = FixedEffect), shape = 21, size = 3, color = "black", show.legend = F) +
    labs(#title = paste(title_prefix, "Fixed Effect Importances with Expected Importances"),
         x = "Fixed Effect Importance", y = "Frequency") +
    scale_fill_manual(values = c("X1" = fill_color,
                           "X2" = fill_color,
                           "X3" = fill_color
                           )) +
    theme_minimal() +
    theme(legend.position = "none",
    strip.text.x = element_text(size = 18),
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12)
    ) + scale_x_continuous(breaks = function(x) pretty(x, n = 4), labels = label_number(accuracy = 0.01)) 
  }
}    

logit_no <- plot_fixed_importances(success_no_bin, "logit", cov_level=0)
logit_low_pos <- plot_fixed_importances(success_low_pos_bin, "logit", cov_level=0.1)
logit_low_neg <- plot_fixed_importances(success_low_neg_bin, "logit", cov_level=-0.1)
logit_high_pos <- plot_fixed_importances(success_high_pos_bin, "logit", cov_level=0.4)
logit_high_neg <- plot_fixed_importances(success_high_neg_bin, "logit", cov_level=-0.4)


poisson_no <- plot_fixed_importances(success_no_pois, "poisson", cov_level=0)
poisson_low_pos <- plot_fixed_importances(success_low_pos_pois, "poisson", cov_level=0.1)
poisson_low_neg <- plot_fixed_importances(success_low_neg_pois, "poisson", cov_level=-0.1)
poisson_high_pos <- plot_fixed_importances(success_high_pos_pois, "poisson", cov_level=0.4)
poisson_high_neg <- plot_fixed_importances(success_high_neg_pois, "poisson", cov_level=-0.4)

logit_no
logit_low_pos
logit_low_neg
logit_high_pos
logit_high_neg

# Install and load the package if needed
if (!requireNamespace("gridExtra", quietly = TRUE)) {
  install.packages("gridExtra")
}
library(gridExtra)


remove_x_axis_label <- function(p) {
  p + theme(axis.title.x = element_blank(),
            legend.position = "none"
            )
}

# Apply the plotting function to create individual plots
logit_no <- remove_x_axis_label(plot_fixed_importances(success_no_bin, "logit", cov_level = 0))
logit_low_pos <- remove_x_axis_label(plot_fixed_importances(success_low_pos_bin, "logit", cov_level = 0.1))
logit_low_neg <- remove_x_axis_label(plot_fixed_importances(success_low_neg_bin, "logit", cov_level = -0.1))
logit_high_pos <- remove_x_axis_label(plot_fixed_importances(success_high_pos_bin, "logit", cov_level = 0.4))
logit_high_neg <- remove_x_axis_label(plot_fixed_importances(success_high_neg_bin, "logit", cov_level = -0.4))

poisson_no <- remove_x_axis_label(plot_fixed_importances(success_no_bin, "poisson", cov_level = 0))
poisson_low_pos <- remove_x_axis_label(plot_fixed_importances(success_low_pos_bin, "poisson", cov_level = 0.1))
poisson_low_neg <- remove_x_axis_label(plot_fixed_importances(success_low_neg_bin, "poisson", cov_level = -0.1))
poisson_high_pos <- remove_x_axis_label(plot_fixed_importances(success_high_pos_bin, "poisson", cov_level = 0.4))
poisson_high_neg <- remove_x_axis_label(plot_fixed_importances(success_high_neg_bin, "poisson", cov_level = -0.4))

combined_plot_logit <- (logit_high_neg / logit_low_neg / logit_no / logit_low_pos / logit_high_pos) +
  plot_layout(ncol = 1, axis_titles = "collect", guides = "auto") +
  plot_annotation(title = NULL, caption = NULL, tag_levels = NULL) +
  labs(x = "Fixed Effect Importance", y = "Frequency")

combined_plot_logit + theme_minimal() + theme(strip.text.x = element_text(size = 18),
                                       axis.title.x = element_text(size = 24),
                                       axis.title.y = element_text(size = 24),
                                       axis.text.x = element_text(size = 12),
                                       axis.text.y = element_text(size = 12)
                                       ) 


combined_plot_logit

combined_plot_poisson <- (poisson_high_neg / poisson_low_neg / poisson_no / poisson_low_pos / poisson_high_pos) +
  plot_layout(ncol = 1, axis_titles = "collect", guides = "auto") +
  plot_annotation(title = NULL, caption = NULL, tag_levels = NULL) +
  labs(x = "Fixed Effect Importance", y = "Frequency")

combined_plot_poisson + theme_minimal() + theme(strip.text.x = element_text(size = 18),
                                       axis.title.x = element_text(size = 24),
                                       axis.title.y = element_text(size = 24),
                                       axis.text.x = element_text(size = 12),
                                       axis.text.y = element_text(size = 12)
                                       ) 


combined_plot_poisson

```




## GELMAN R2
Here, we compute and visualize the Gelman conditional R² metrics for each model. This metric gives insight into the proportion of variance explained by the fixed effects in the models.
```{r}

beta <- c(1, sqrt(2), sqrt(3))
rho_values <- c(0, 0.1, -0.1, 0.4, -0.4)

dist_logit <- pi^2/3
dist_poisson <- log(1+1/exp(0 + 0.5*1))
dist_probit <- 1


variance_explained <- data.frame(
  rho = rho_values,
  expected_logit = numeric(length(rho_values)),
  expected_poisson = numeric(length(rho_values)),
  expected_probit = numeric(length(rho_values)),
  R2_marginal_logit = numeric(length(rho_values)),
  R2_conditional_logit = numeric(length(rho_values)),
  R2_marginal_poisson = numeric(length(rho_values)),
  R2_conditional_poisson = numeric(length(rho_values))
)

for (i in 1:length(rho_values)) {
  rho <- rho_values[i]
  
  var_eta <- (sum((beta^2)) + 
                2*(beta[1] * beta[2] * rho
               + beta[1] * beta[3] * rho
               + beta[3] * beta[2] * rho)
               + 1)
  
  if (rho==0){
    variance_explained[i, "expected_logit"] <- 1/(var_eta + dist_logit)
    variance_explained[i, "expected_poisson"] <- 1/(var_eta + dist_poisson)
    variance_explained[i, "expected_probit"] <- 1/(var_eta + dist_probit)
  } else {
    variance_explained[i, "expected_logit"] <- 0
    variance_explained[i, "expected_poisson"] <- 0
  }

  R2_marginal_logit <- (var_eta-1) / (var_eta + dist_logit)
  R2_conditional_logit <- (var_eta) / (var_eta + dist_logit)
  
  R2_marginal_poisson <- (var_eta-1) / (var_eta + dist_poisson)
  R2_conditional_poisson <- (var_eta) / (var_eta + dist_poisson)
  
  variance_explained[i, "R2_marginal_logit"] <- R2_marginal_logit
  variance_explained[i, "R2_conditional_logit"] <- R2_conditional_logit
  variance_explained[i, "R2_marginal_poisson"] <- R2_marginal_poisson
  variance_explained[i, "R2_conditional_poisson"] <- R2_conditional_poisson
}



```



```{r}
library(ggplot2)
library(dplyr)


plot_r2_correlation_level <- function(data, model_name, correlation_label, correlation_color) {

    r2_data <- data.frame(
      Type = rep(c("Marginal", "Conditional"), each = length(data)),
      Value = c(sapply(data, function(x) x[[model_name]]$r2m),
                sapply(data, function(x) x[[model_name]]$r2c))
    )
    r2_data$Type <- factor(r2_data$Type, levels = c("Marginal", "Conditional"))
    
    means <- r2_data %>%
    group_by(Type) %>%
    summarise(Mean = mean(Value))
    

    expected_values <- variance_explained %>%
        filter(rho == as.numeric(correlation_label)) %>%
        summarise(
          R2_Marginal = ifelse(model_name == "logit", R2_marginal_logit, R2_marginal_poisson),
          R2_Conditional = ifelse(model_name == "logit", R2_conditional_logit, R2_conditional_poisson)
        )


    expected_lines <- data.frame(
      Type = c("Marginal", "Conditional"),
      Value = c(expected_values$R2_Marginal, expected_values$R2_Conditional),
      Measure = "Expected"
    )
    expected_lines$Type <- factor(expected_lines$Type, levels = c("Marginal", "Conditional"))


    plot <- ggplot(r2_data, aes(x = Value, fill = Type)) +
        geom_histogram(bins = 30, alpha = 0.7) +
        facet_wrap(~ Type, scales = "free") +
        geom_vline(data = expected_lines, aes(xintercept = Value, color = Measure), linetype = "dashed", linewidth = 1) +
        geom_point(data = means, aes(x = Mean, y = 0, fill = Type), shape = 21, size = 3, color = "black") +
        scale_fill_manual(values = c(Marginal = correlation_color, Conditional = correlation_color)) +
        scale_color_manual(values = c(Expected = "green")) +
        labs(#title = paste("R-squared Values for", model_name, "Model: rho =", correlation_label),
             x = "R2 Value", y = "Frequency") +
        theme_minimal() +
        theme(legend.position = "none",
              strip.text.x = element_text(size = 18),
              axis.title.x = element_text(size = 24),
              axis.title.y = element_text(size = 24),
              axis.text.x = element_text(size = 12),
              axis.text.y = element_text(size = 12))

    return(plot)
}

stoffel_logit_no <- c(Stoffel_logit_R2m_no, Stoffel_logit_R2c_no)
stoffel_logit_low_pos <- c(Stoffel_logit_R2m_low_pos, Stoffel_logit_R2c_low_pos)
stoffel_logit_low_neg <- c(Stoffel_logit_R2m_low_neg, Stoffel_logit_R2c_low_neg)
stoffel_logit_high_pos <- c(Stoffel_logit_R2m_high_pos, Stoffel_logit_R2c_high_pos)
stoffel_logit_high_neg <- c(Stoffel_logit_R2m_high_neg, Stoffel_logit_R2c_high_neg)


r2_logit_no <- plot_r2_correlation_level(success_no_bin, "logit", 0, "#C6CDF7")
r2_logit_low_pos <- plot_r2_correlation_level(success_low_pos_bin, "logit", 0.1, "#B6D7F7")
r2_logit_low_neg <- plot_r2_correlation_level(success_low_neg_bin, "logit", -0.1, "#D6C6E7")
r2_logit_high_pos <- plot_r2_correlation_level(success_high_pos_bin, "logit", 0.4, "#C6F7CD")
r2_logit_high_neg <- plot_r2_correlation_level(success_high_neg_bin, "logit", -0.4, "#E6C6DF")

r2_poisson_no <- plot_r2_correlation_level(success_no_bin, "poisson", 0, "#C6CDF7")
r2_poisson_low_pos <- plot_r2_correlation_level(success_low_pos_bin, "poisson", 0.1, "#B6D7F7")
r2_poisson_low_neg <- plot_r2_correlation_level(success_low_neg_bin, "poisson", -0.1, "#D6C6E7")
r2_poisson_high_pos <- plot_r2_correlation_level(success_high_pos_bin, "poisson", 0.4, "#C6F7CD")
r2_poisson_high_neg <- plot_r2_correlation_level(success_high_neg_bin, "poisson", -0.4, "#E6C6DF")

r2_logit_high_neg 
r2_logit_low_neg
r2_logit_no
r2_logit_low_pos
r2_logit_high_pos

r2_poisson_high_neg
r2_poisson_low_neg
r2_poisson_no
r2_poisson_low_pos
r2_poisson_high_pos


variance_explained
0.1337958*2
0.1337958*3

```


```{r}

plot_r2_correlation_level_with_stoffel <- function(data, model_name, correlation_label, correlation_color, stoffel_values) {

    r2_data <- data.frame(
        Type = rep(c("Marginal", "Conditional"), each = length(data)),
        Value = c(sapply(data, function(x) x[[model_name]]$r2m),
                  sapply(data, function(x) x[[model_name]]$r2c))
    )
    r2_data$Type <- factor(r2_data$Type, levels = c("Marginal", "Conditional"))
    
    means <- r2_data %>%
        group_by(Type) %>%
        summarise(Mean = mean(Value))


    expected_values <- variance_explained %>%
        filter(rho == as.numeric(correlation_label)) %>%
        summarise(
            R2_Marginal = ifelse(model_name == "logit", R2_marginal_logit, R2_marginal_poisson),
            R2_Conditional = ifelse(model_name == "logit", R2_conditional_logit, R2_conditional_poisson)
        )


    expected_lines <- data.frame(
        Type = c("Marginal", "Conditional"),
        Value = c(expected_values$R2_Marginal, expected_values$R2_Conditional),
        Measure = "Expected"
    )
    expected_lines$Type <- factor(expected_lines$Type, levels = c("Marginal", "Conditional"))


    stoffel_points <- data.frame(
        Type = c("Marginal", "Conditional"),
        Value = stoffel_values,
        Measure = "Stoffel"
    )
    stoffel_points$Type <- factor(stoffel_points$Type, levels = c("Marginal", "Conditional"))


    plot <- ggplot(r2_data, aes(x = Value, fill = Type)) +
        geom_histogram(bins = 30, alpha = 0.7) +
        facet_wrap(~ Type, scales = "free") +
        geom_vline(data = expected_lines, aes(xintercept = Value, color = Measure), linetype = "dashed", linewidth = 1) +
        geom_point(data = means, aes(x = Mean, y = 0, fill = Type), shape = 21, size = 3, color = "black") +
        geom_point(data = stoffel_points, aes(x = Value, y = 0, color = Measure), size = 3) +
        scale_fill_manual(values = c(Marginal = correlation_color, Conditional = correlation_color)) +
        scale_color_manual(values = c(Expected = "green", Stoffel = "orange")) +
        labs(#title = paste("R-squared Values for", model_name, "Model: rho =", correlation_label),
             x = "R2 Value", y = "Frequency") +
        theme_minimal() +
        theme(legend.position = "none",
              strip.text.x = element_text(size = 18),
              axis.title.x = element_text(size = 24),
              axis.title.y = element_text(size = 24),
              axis.text.x = element_text(size = 12),
              axis.text.y = element_text(size = 12))

    return(plot)
}

# Example usage
stoffel_logit_no <- c(Stoffel_logit_R2m_no, Stoffel_logit_R2c_no)
stoffel_logit_low_pos <- c(Stoffel_logit_R2m_low_pos, Stoffel_logit_R2c_low_pos)
stoffel_logit_low_neg <- c(Stoffel_logit_R2m_low_neg, Stoffel_logit_R2c_low_neg)
stoffel_logit_high_pos <- c(Stoffel_logit_R2m_high_pos, Stoffel_logit_R2c_high_pos)
stoffel_logit_high_neg <- c(Stoffel_logit_R2m_high_neg, Stoffel_logit_R2c_high_neg)

stoffel_poisson_no <- c(Stoffel_pois_R2m_no, Stoffel_pois_R2c_no)
stoffel_poisson_low_pos <- c(Stoffel_pois_R2m_low_pos, Stoffel_pois_R2c_low_pos)
stoffel_poisson_low_neg <- c(Stoffel_pois_R2m_low_neg, Stoffel_pois_R2c_low_neg)
stoffel_poisson_high_pos <- c(Stoffel_pois_R2m_high_pos, Stoffel_pois_R2c_high_pos)
stoffel_poisson_high_neg <- c(Stoffel_pois_R2m_high_neg, Stoffel_pois_R2c_high_neg)

# Create the plots
r2_logit_no <- plot_r2_correlation_level_with_stoffel(success_no_bin, "logit", 0, "#C6CDF7", stoffel_logit_no)
r2_logit_low_pos <- plot_r2_correlation_level_with_stoffel(success_low_pos_bin, "logit", 0.1, "#B6D7F7", stoffel_logit_low_pos)
r2_logit_low_neg <- plot_r2_correlation_level_with_stoffel(success_low_neg_bin, "logit", -0.1, "#D6C6E7", stoffel_logit_low_neg)
r2_logit_high_pos <- plot_r2_correlation_level_with_stoffel(success_high_pos_bin, "logit", 0.4, "#C6F7CD", stoffel_logit_high_pos)
r2_logit_high_neg <- plot_r2_correlation_level_with_stoffel(success_high_neg_bin, "logit", -0.4, "#E6C6DF", stoffel_logit_high_neg)

r2_poisson_no <- plot_r2_correlation_level_with_stoffel(success_no_bin, "poisson", 0, "#C6CDF7", stoffel_poisson_no)
r2_poisson_low_pos <- plot_r2_correlation_level_with_stoffel(success_low_pos_bin, "poisson", 0.1, "#B6D7F7", stoffel_poisson_low_pos)
r2_poisson_low_neg <- plot_r2_correlation_level_with_stoffel(success_low_neg_bin, "poisson", -0.1, "#D6C6E7", stoffel_poisson_low_neg)
r2_poisson_high_pos <- plot_r2_correlation_level_with_stoffel(success_high_pos_bin, "poisson", 0.4, "#C6F7CD", stoffel_poisson_high_pos)
r2_poisson_high_neg <- plot_r2_correlation_level_with_stoffel(success_high_neg_bin, "poisson", -0.4, "#E6C6DF", stoffel_poisson_high_neg)

r2_logit_high_neg 
r2_logit_low_neg
r2_logit_no
r2_logit_low_pos
r2_logit_high_pos

r2_poisson_high_neg
r2_poisson_low_neg
r2_poisson_no
r2_poisson_low_pos
r2_poisson_high_pos


r2_data_high_neg <- data.frame(
    Type = rep(c("Marginal", "Conditional"), each = length(success_high_neg_bin)),
    Value = c(sapply(success_high_neg_bin, function(x) x[["poisson"]]$r2m),
              sapply(success_high_neg_bin, function(x) x[["poisson"]]$r2c))
)
r2_data_high_neg$Type <- factor(r2_data_high_neg$Type, levels = c("Marginal", "Conditional"))

means_high_neg <- r2_data_high_neg %>%
    group_by(Type) %>%
    summarise(Mean = mean(Value))

r2_data_low_neg <- data.frame(
    Type = rep(c("Marginal", "Conditional"), each = length(success_low_neg_bin)),
    Value = c(sapply(success_low_neg_bin, function(x) x[["poisson"]]$r2m),
              sapply(success_low_neg_bin, function(x) x[["poisson"]]$r2c))
)
r2_data_low_neg$Type <- factor(r2_data_low_neg$Type, levels = c("Marginal", "Conditional"))

means_low_neg <- r2_data_low_neg %>%
    group_by(Type) %>%
    summarise(Mean = mean(Value))


r2_data_no <- data.frame(
    Type = rep(c("Marginal", "Conditional"), each = length(success_no_bin)),
    Value = c(sapply(success_no_bin, function(x) x[["poisson"]]$r2m),
              sapply(success_no_bin, function(x) x[["poisson"]]$r2c))
)
r2_data_no$Type <- factor(r2_data_no$Type, levels = c("Marginal", "Conditional"))

means_no <- r2_data_no %>%
    group_by(Type) %>%
    summarise(Mean = mean(Value))

r2_data_low_pos <- data.frame(
    Type = rep(c("Marginal", "Conditional"), each = length(success_low_pos_bin)),
    Value = c(sapply(success_low_pos_bin, function(x) x[["poisson"]]$r2m),
              sapply(success_low_pos_bin, function(x) x[["poisson"]]$r2c))
)
r2_data_low_pos$Type <- factor(r2_data_low_pos$Type, levels = c("Marginal", "Conditional"))

means_low_pos <- r2_data_low_pos %>%
    group_by(Type) %>%
    summarise(Mean = mean(Value))

r2_data_high_pos <- data.frame(
    Type = rep(c("Marginal", "Conditional"), each = length(success_high_pos_bin)),
    Value = c(sapply(success_high_pos_bin, function(x) x[["poisson"]]$r2m),
              sapply(success_high_pos_bin, function(x) x[["poisson"]]$r2c))
)
r2_data_high_pos$Type <- factor(r2_data_high_pos$Type, levels = c("Marginal", "Conditional"))

means_high_pos <- r2_data_high_pos %>%
    group_by(Type) %>%
    summarise(Mean = mean(Value))



means_high_neg
means_low_neg
means_no
means_low_pos
means_high_pos

variance_explained

abs(0.848 - 0.8766533)
abs(0.934 - 0.9603305)

```


```{r}
r2_logit_no <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_no_bin, "logit", 0, "#C6CDF7", stoffel_logit_no))
r2_logit_low_pos <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_low_pos_bin, "logit", 0.1, "#B6D7F7", stoffel_logit_low_pos))
r2_logit_low_neg <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_low_neg_bin, "logit", -0.1, "#D6C6E7", stoffel_logit_low_neg))
r2_logit_high_pos <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_high_pos_bin, "logit", 0.4, "#C6F7CD", stoffel_logit_high_pos))
r2_logit_high_neg <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_high_neg_bin, "logit", -0.4, "#E6C6DF", stoffel_logit_high_neg))

r2_poisson_no <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_no_bin, "poisson", 0, "#C6CDF7", stoffel_poisson_no))
r2_poisson_low_pos <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_low_pos_bin, "poisson", 0.1, "#B6D7F7", stoffel_poisson_low_pos))
r2_poisson_low_neg <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_low_neg_bin, "poisson", -0.1, "#D6C6E7", stoffel_poisson_low_neg))
r2_poisson_high_pos <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_high_pos_bin, "poisson", 0.4, "#C6F7CD", stoffel_poisson_high_pos))
r2_poisson_high_neg <- remove_x_axis_label(plot_r2_correlation_level_with_stoffel(success_high_neg_bin, "poisson", -0.4, "#E6C6DF", stoffel_poisson_high_neg))

combined_plot_r2_logit <- (r2_logit_high_neg / r2_logit_low_neg / r2_logit_no / r2_logit_low_pos / r2_logit_high_pos) +
  plot_layout(ncol = 1, axis_titles = "collect", guides = "auto") +
  plot_annotation(title = NULL, caption = NULL, tag_levels = NULL) +
  labs(x = "Fixed Effect Importance", y = "Frequency")

combined_plot_r2_logit + theme_minimal() + theme(strip.text.x = element_text(size = 18),
                                       axis.title.x = element_text(size = 24),
                                       axis.title.y = element_text(size = 24),
                                       axis.text.x = element_text(size = 12),
                                       axis.text.y = element_text(size = 12)
                                       ) 

combined_plot_r2_logit

combined_plot_r2_poisson <- (r2_poisson_high_neg / r2_poisson_low_neg / r2_poisson_no / r2_poisson_low_pos / r2_poisson_high_pos) +
  plot_layout(ncol = 1, axis_titles = "collect", guides = "auto") +
  plot_annotation(title = NULL, caption = NULL, tag_levels = NULL) +
  labs(x = "Fixed Effect Importance", y = "Frequency")

combined_plot_r2_poisson + theme_minimal() + theme(strip.text.x = element_text(size = 18),
                                       axis.title.x = element_text(size = 24),
                                       axis.title.y = element_text(size = 24),
                                       axis.text.x = element_text(size = 12),
                                       axis.text.y = element_text(size = 12)
                                       ) 


combined_plot_r2_poisson
```



```{r}
plot_folder <- "/Users/augustarnstad/Library/CloudStorage/OneDrive-NTNU/Semester_10/Master/Latex/Figures/Simulation study"

# Check if the folder exists, if not, create it
if (!dir.exists(plot_folder)) {
  dir.create(plot_folder)
}

ggsave(filename="Random_logit.png", plot=random_logit_plot, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Random_poisson.png", plot=random_poisson_plot, path=plot_folder, width = 10, height = 6, dpi = 300)

ggsave(filename="Fixed_no_logit.png", plot=logit_no, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Fixed_no_poisson.png", plot=poisson_no, path=plot_folder, width = 10, height = 6, dpi = 300)

ggsave(filename="Fixed_low_pos_logit.png", plot=logit_low_pos, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Fixed_low_pos_poisson.png", plot=poisson_low_pos, path=plot_folder, width = 10, height = 6, dpi = 300)

ggsave(filename="Fixed_high_pos_logit.png", plot=logit_high_pos, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Fixed_high_pos_poisson.png", plot=poisson_high_pos, path=plot_folder, width = 10, height = 6, dpi = 300)

ggsave(filename="Fixed_low_neg_logit.png", plot=logit_low_neg, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Fixed_low_neg_poisson.png", plot=poisson_low_neg, path=plot_folder, width = 10, height = 6, dpi = 300)

ggsave(filename="Fixed_high_neg_logit.png", plot=logit_high_neg, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Fixed_high_neg_poisson.png", plot=poisson_high_neg, path=plot_folder, width = 10, height = 6, dpi = 300)


ggsave(filename="Fixed_combined_logit.png", plot=combined_plot_logit, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Fixed_combined_poisson.png", plot=combined_plot_poisson, path=plot_folder, width = 10, height = 6, dpi = 300)


ggsave(filename="R2_logit_no.png", plot=r2_logit_no, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_logit_low_pos.png", plot=r2_logit_low_pos, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_logit_low_neg.png", plot=r2_logit_low_neg, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_logit_high_pos.png", plot=r2_logit_high_pos, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_logit_high_neg.png", plot=r2_logit_high_neg, path=plot_folder, width = 10, height = 6, dpi = 300)

ggsave(filename="R2_poisson_no.png", plot=r2_poisson_no, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_poisson_low_pos.png", plot=r2_poisson_low_pos, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_poisson_low_neg.png", plot=r2_poisson_low_neg, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_poisson_high_pos.png", plot=r2_poisson_high_pos, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_poisson_high_neg.png", plot=r2_poisson_high_neg, path=plot_folder, width = 10, height = 6, dpi = 300)

ggsave(filename="R2_combined_logit.png", plot=combined_plot_r2_logit, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_combined_poisson.png", plot=combined_plot_r2_poisson, path=plot_folder, width = 10, height = 6, dpi = 300)

```


